### ISSUE TITLE
Public site instabilities

### ISSUE THREAD

**Issue by akiledal** [Geo-omics/mibios#37]
There have been issues with LSA's hosting capabilities in recent days that are impacting the openshift instance. @robert102 has more details. It should stabilize, but they suggested we could potentially migrate hosting over to an openshift instance managed by ITS that would be more stable, however it would also be more expensive.

**Comment by robert102** [comment]
Per logs no outage since the evening of June 10th
On June 13th successfully loaded frontpage every 15s for 8h during work hours.

**Comment by robert102** [comment]
![image](https://github.com/Geo-omics/mibios/assets/50373408/9d73b1cd-3723-4b85-b691-c0d306d55cb5)
